#include <gcsa/resources.h>
#include <gcsa/workspace.h>
#include <atomic>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <iterator>
#include <thread>
#include <unistd.h>
using namespace gcsa;
static void require(bool v) { if(!v) { std::fprintf(stderr,"workspace test failure\n"); std::abort(); } }
static bool invalid(BuildWorkspace& w,const ArtifactIdentity& i) { try { w.validate_artifact(i,logical_file_id_t(7),physical_shard_id_t(9)); } catch(const std::runtime_error&) { return true; } return false; }
int main() {
  MemoryBudget b(100,10); MemoryBudget::Reservation first=b.reserve(90,"first"); std::atomic<bool> started(false),got(false);
  std::thread waiter([&]{started=true;MemoryBudget::Reservation second=b.reserve(1,"second");got=true;}); while(!started) std::this_thread::yield(); std::this_thread::sleep_for(std::chrono::milliseconds(25)); require(!got); first=MemoryBudget::Reservation(); waiter.join(); require(got && b.stats().current==0 && b.stats().maximum==90); bool over=false; try { b.reserve(91,"too-large"); } catch(const std::runtime_error&) { over=true; } require(over);
  char root[]="/tmp/gcsa-workspace-XXXXXX"; require(mkdtemp(root)); BuildWorkspace::Settings sem,op; sem["k"]="64"; op["threads"]="2"; BuildWorkspace w(root,sem,op,BuildWorkspace::NEW_WORKSPACE); require(access((std::string(root)+"/build.json").c_str(),F_OK)==0);
  bool new_refused=false, semantic_refused=false; try { BuildWorkspace again(root,sem,op,BuildWorkspace::NEW_WORKSPACE); } catch(const std::runtime_error&) { new_refused=true; } BuildWorkspace::Settings changed=sem; changed["k"]="65"; try { BuildWorkspace bad(root,changed); } catch(const std::runtime_error&) { semantic_refused=true; } require(new_refused && semantic_refused); BuildWorkspace resumed(root,sem,BuildWorkspace::Settings());
  ArtifactIdentity id("phase/task","sort stage","relative/path","payload-kind"); require(!resumed.task_completed(id.task,id.phase)); std::vector<uint8_t> payload(2*1024*1024+17); for(size_t n=0;n<payload.size();++n) payload[n]=uint8_t(n); BuildWorkspace::ArtifactWriter writer=resumed.open_artifact(id,logical_file_id_t(7),physical_shard_id_t(9),"key","a-z"); writer.write(&payload[0],1024*1024); writer.write(&payload[1024*1024],payload.size()-1024*1024); BuildWorkspace::ArtifactRef ref=writer.finish(3); std::vector<BuildWorkspace::ArtifactRef> refs(1,ref); resumed.commit_task(id.task,id.phase,refs,std::vector<std::string>(1,"input-checksum")); resumed.validate_artifact(id,logical_file_id_t(7),physical_shard_id_t(9)); require(resumed.task_completed(id.task,id.phase)); require(resumed.read_artifact_payload(id,logical_file_id_t(7),physical_shard_id_t(9),payload.size())==payload); std::string restored=std::string(root)+"/restored.payload"; resumed.restore_artifact(id,logical_file_id_t(7),physical_shard_id_t(9),restored,7777); { std::ifstream input(restored.c_str(),std::ios::binary); std::vector<uint8_t> copy((std::istreambuf_iterator<char>(input)),std::istreambuf_iterator<char>()); require(copy==payload); } require(unlink(restored.c_str())==0);
  std::string good=resumed.artifact_path(id,logical_file_id_t(7),physical_shard_id_t(9)); std::string unmarked=resumed.artifact_path(ArtifactIdentity("other","phase","uncommitted","bin"),logical_file_id_t(1),physical_shard_id_t(2)); BuildWorkspace::ArtifactWriter orphan=resumed.open_artifact(ArtifactIdentity("other","phase","uncommitted","bin"),logical_file_id_t(1),physical_shard_id_t(2)); orphan.write(payload.data(),7); orphan.finish(1); std::string renamed=std::string(root)+"/renamed-successor.bin"; require(rename(unmarked.c_str(),renamed.c_str())==0); { std::ofstream stale((std::string(root)+"/stale.partial").c_str()); stale<<"partial"; } resumed.recover(); require(access(renamed.c_str(),F_OK)!=0 && access((std::string(root)+"/stale.partial").c_str(),F_OK)!=0); resumed.validate_artifact(id,logical_file_id_t(7),physical_shard_id_t(9));
  { std::fstream f(good.c_str(),std::ios::in|std::ios::out|std::ios::binary); f.seekp(54); char x=127; f.write(&x,1); } require(invalid(resumed,id)); BuildWorkspace::ArtifactWriter repair=resumed.open_artifact(id,logical_file_id_t(7),physical_shard_id_t(9),"key","a-z"); repair.write(payload.data(),payload.size()); ref=repair.finish(3); refs[0]=ref; resumed.commit_task(id.task,id.phase,refs); { std::fstream f(good.c_str(),std::ios::in|std::ios::out|std::ios::binary); f.seekp(0,std::ios::end); std::streamoff n=f.tellp(); f.close(); require(truncate(good.c_str(),n-1)==0); } require(invalid(resumed,id));
  DiskBudget disk(root,1,0); std::string why; require(!disk.can_reserve(2,&why) && !why.empty()); return 0;
}
